main.py, state.py, static/stylesheet.css, templates/home_page.html
It's fairly rudimentary, but this code allows us to at least track logins and store listings. I've also added a toy session bar, as we talked about. Please have a look-see and merge if it looks good.
=> Add session handling and listings model

main.py, templates/index.html
I, er, already tested on prod- https://hosted-caravel.appspot.com
=> Limit number of results on main page and add display: float.

templates/index.html
fixing the row alignment of homepage to show only 4 listings per row
=> fixing rows in homepage

static/default.css, templates/header.html, templates/layout.html
- Add user dropdown that properly drops
- Add top margin to navbar
=> Fixing user dropdown

app.yaml, cron.yaml, live_migration.py, main.py, models.py, photos.py, requirements.txt, search.py, static/default.css, static/index.css, templates/index.html, templates/listing_show.html, vendor/cloudstorage/__init__.py, vendor/cloudstorage/api_utils.py, vendor/cloudstorage/cloudstorage_api.py, vendor/cloudstorage/common.py, vendor/cloudstorage/errors.py, vendor/cloudstorage/rest_api.py, vendor/cloudstorage/storage_api.py, vendor/cloudstorage/test_utils.py
This pull request adds migration, serving, and expiration, and fixes #10.
=> Add photo support

circle.yml, requirements.txt
This (third-party) service automatically deploys the latest version of the code whenever one of us pushes to master. If it works, I'll add support for deploying from all branches.
=> Add support for CircleCI

search.py
Not much more to add. This one was a brainfart on my part.
=> Display newest entries first

caravel/controllers/listings.py, caravel/policy.py, caravel/templates/email/inquiry.html, caravel/templates/email/inquiry.txt, caravel/templates/email/welcome.html, caravel/templates/email/welcome.txt
The above is mostly what it looks like, modulo me monkeying (ahem) with the footer. For the full experience, make a form and POST to:
https://add-email-templates-dot-hosted-caravel.appspot.com/ and
https://add-email-templates-dot-hosted-caravel.appspot.com/large-childrens-circus-tent/inquiry
As an easy way to do that, open the first URL in Chrome, open the console, then run either of:
var data = new FormData;
data.append("email", "youremail@uchicago.edu"); // must be @uchicago.edu!
fetch("/", {method: "POST", body: data}).then(function(x) { console.log(x.status); });
fetch("/large-childrens-circus-tent/inquiry", {method: "POST", body: data}).then(function(x) { console.log(x.status); });
then look for the two "200s". You will also then receive two emails.
=> Add rudimentary support for registration and inquiry emails

caravel/storage/helpers.py
Approved a pull request without looking too closely. Fixed the problem here.
=> fixing typo from add_search that I overlooked

app.yaml
In this day and age, it's pretty silly not to; costs us pretty much nuffin'.
=> Use HTTPS by default

.gitignore
Fairly self-explanatory. This thing pops up on Mac OS X when using the Finder.
=> Add .DS_Store to .gitignore.

caravel/templates/layout.html
Derp
Blue link: http://fix-bootstrap-again-dot-hosted-caravel.appspot.com
=> Fix missing close tag (sigh)

caravel/templates/listing_show.html
=> adding carosel to view images

caravel/static/default.css
Played around with it, and 400 seems the most "neutral." Thoughts?
(x-ref with #51)
=> Lighten Roboto from 900 to 400

caravel/__init__.py, caravel/daemons/migration.py, caravel/daemons/replication.py, caravel/storage/entities.py, caravel/storage/helpers.py, caravel/testing/integration_test.py, cron.yaml
_so jetlagged :(_
I honestly haven't even tested this. I would advise against merging until I do; just thought I'd make adding the seller flag easier.
=> Add basic support for migration

caravel/__init__.py, caravel/static/default.css, caravel/templates/index.html, caravel/utils.py
Fairly self-explanatory. I used black, but am happy to use whatever color you think is best.
http://add-posting-times-dot-hosted-caravel.appspot.com/
=> Display age of posted listings

caravel/templates/header.html
=> Trigger search on click

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/daemons/migration.py, caravel/daemons/replication.py, caravel/storage/config.py, caravel/storage/entities.py, caravel/storage/helpers.py, caravel/templates/email/welcome.html, caravel/templates/email/welcome.txt, caravel/templates/listing_form.html
N.B. This pull request is dependent on #57.
Largely, this just adds the .put() call and the key stuff I was talking about. I haven't done anything with the "place inquiry" form, but that can come next.
=> Add persistence to /new

caravel/storage/cache.py, caravel/storage/helpers.py
This will help reduce end-user latency at a slight cost in read operations.
=> Fetch entities on the main page in parallel

circle.yml
It's a little hacky, but will hopefully catch errors in the future.
=> Ensure that the site works on prod

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/templates/header.html, caravel/templates/listing_form.html, caravel/templates/listings/fullpage.html
Again, because redirects are wonky, this would throw a 405 before.
Clicky link: https://make-edit-send-emails-dot-hosted-caravel.appspot.com
=> Ensure that edit listing sends emails

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/templates/email/inquiry.html, caravel/templates/email/inquiry.txt
I was getting a 405 before, because redirects are _the absolute worst_. I believe this pull request fixes it.
Anyway, test instance is https://ensure-inquiry-sends-emails-dot-hosted-caravel.appspot.com.
=> Ensure that the place inquiry view sends emails

caravel/controllers/forms.py, caravel/static/default.css, caravel/templates/listing_form.html
I figure knitting the form inputs with the output can happen once the 405 fixes are landed.
=> Add rudimentary support for categories in the forms

caravel/controllers/listings.py, caravel/templates/layout.html
Er, yeah — was thinking "created" for "saved but not public," and "published" for "visible to buyers." Thoughts?
=> Add flash notices to guide users through posting

caravel/controllers/listings.py, caravel/static/default.css, caravel/templates/header.html
=> adding new listing button

caravel/templates/listings/inline.html
See https://hosted-caravel.appspot.com. (This was a bad review- sorry about that.)
=> Fix broken links on home page

caravel/static/default.css, caravel/templates/listings/fullpage.html
While I understand the sentiment to put the "This is my listing" button at the top, what do you think of this other option, which is cleaner and not too difficult to see since text isn't usually too long.
=> adding margin below claim listing buttom

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/daemons/replication.py, caravel/storage/entities.py, caravel/templates/listings/inline.html
Fairly basic. I wasn't sure how to display multiple categories with the funny categories tag, so I left as-is.
=> Add support for categories

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/static/default.css, caravel/static/js/thumbnails.js, caravel/storage/entities.py, caravel/storage/photos.py, caravel/templates/listing_form.html, caravel/templates/listings/inline.html
See attached photo of UX:
One potential problem is that this means any user can upload images to the site; I'm not sure what to do here.
=> Add image upload support

caravel/static/default.css, caravel/templates/index.html, caravel/templates/index_continuation.html, caravel/templates/listing_form.html, caravel/templates/listing_show.html, caravel/templates/listings/fullpage.html, caravel/templates/listings/inline.html, caravel/utils.py
Reverts uchicago-sg/caravel#88
=> Revert "Remove most styles and use Bootstrap defaults"

caravel/static/default.css, caravel/storage/photos.py, caravel/templates/header.html, caravel/templates/listing_form.html, caravel/templates/listings/inline.html
Fairly rudimentary, but these things were bugging me.
https://fix-styles-dot-hosted-caravel.appspot.com/
=> Readjust spacing in Marketplace styles

caravel/controllers/forms.py
=> Allow price to be $0.

caravel/policy.py
=> Allow Booth emails

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/storage/entities.py
Previously, it would throw a 500. Now it does not (I think).
=> Allow users to upload photos with new listings

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/static/default.css, caravel/storage/entities.py, caravel/templates/header.html, caravel/templates/layout.html, caravel/utils.py
This adds a top bar with all categories, in order, plus a new "free" category.
Test URL: https://add-categories-bar-dot-hosted-caravel.appspot.com
=> Add categories bar

caravel/controllers/forms.py, caravel/storage/entities.py
Currently, https://hosted-caravel.appspot.com/?q=free comes up with a lot of things that are not $0.
=> Avoid overloading the world "free."

caravel/storage/helpers.py
Fixes #105.
Test URL: https://ensure-that-ands-work-dot-hosted-caravel.appspot.com/?q=jarcher@uchicago.edu+jarcher@uchicago.edu
=> Ensure that duplicate keywords don't break things.

caravel/controllers/listings.py, caravel/storage/cache.py, caravel/storage/entities.py, caravel/storage/helpers.py
Fairly rudimentary. I believe this fixes the bugs we were experiencing earlier.
=> Make search queries AND.

caravel/controllers/listings.py, caravel/static/default.css, caravel/templates/header.html, caravel/templates/index.html, caravel/templates/list_button.html, caravel/templates/thumbnail_button.html
=> fixing user button

caravel/controllers/listings.py, caravel/templates/listings/fullpage.html
Solves #93.
Test URL: https://add-unpublish-button-dot-hosted-caravel.appspot.com
=> Add unpublish button

caravel/controllers/listings.py, caravel/templates/layout.html
The text is as specified in #117.
=> Add CLI disclaimer on first visit

caravel/controllers/listings.py, caravel/storage/config.py, requirements.txt, vendor/sendgrid/__init__.py, vendor/sendgrid/client.py, vendor/sendgrid/exceptions.py, vendor/sendgrid/message.py, vendor/sendgrid/resources/api_keys.py, vendor/sendgrid/resources/asm_global_suppressions.py, vendor/sendgrid/resources/asm_groups.py, vendor/sendgrid/resources/asm_suppressions.py, vendor/sendgrid/resources/suppressions.py, vendor/sendgrid/sendgrid.py, vendor/sendgrid/version.py, vendor/smtpapi/__init__.py
Because Google still hasn't approved our request for >100 emails/day >:|
Test at: https://switch-to-sendgrid-dot-hosted-caravel.appspot.com
=> Switch to SendGrid

caravel/storage/entities.py
Once this is fixed, we still need to get people to click the link again.
=> Make sure old listings actually have an admin_key.

caravel/static/humans.txt, caravel/static/robots.txt
Right now we're blocking the Internet Archive, which seems like a shame.
=> Add {robots,humans}.txt

caravel/controllers/listings.py
Derp. This code is in serious need of refactoring and/or test coverage.
=> Allow empty price without throwing 500

circle.yml
=> Actually push development branches to App Engine

caravel/controllers/listings.py, caravel/daemons/replication.py, caravel/storage/entities.py, caravel/storage/photos.py, caravel/templates/listings/fullpage.html, caravel/templates/listings/thumbnail.html, caravel/testing/integration_test.py
Ugh... this again. Whenever people edit thumbnails, the "thumbnail" is actually set to the full-size image.
Since this is the first merge of the new site, we'll need to be _really careful_ before pushing it live.
=> Fix handling of thumbnails

caravel/storage/cache.py, caravel/storage/photos.py
This makes the test site upload-able.
https://fix-pictures-on-test-instance-dot-caravel-code-reviews.appspot.com/
Unfortunately, emails still don't work >.>
=> Fix photos on test site

caravel/controllers/listings.py
It might be good to fix this in a cleaner way (i.e. reporting failure to the user) long term, but I'm not sure how to do that. Maybe a custom Flask validation step?
=> Relax limits on Marketplace inquiries submissions

caravel/controllers/listings.py
This person is back! Time to drop the banhammer.
#127
=> Temporarily blacklist globarry24

caravel/controllers/forms.py, caravel/controllers/listings.py, caravel/policy/__init__.py, caravel/policy/eligible_users.py, caravel/storage/config.py, caravel/templates/email/inquiry.html, caravel/templates/email/inquiry.txt, caravel/tests/test_listings.py
It's, er, a lot — I'm trying to pull out the policy aspects of Marketplace from the glue code of listings.py.
=> Simplify Controllers

caravel/storage/email.py
Hopefully this'll help debug some of these missing email problems.
=> Add email logging

caravel/templates/listings/thumbnail.html
=> Fix category images

caravel/storage/config.py, caravel/storage/slack.py
There's nothing plugged into `listings.py` yet — I'll add that after the tests are merged in.
=> Add Slack webhook integration

caravel/policy/eligible_users.py
Says it on the can. Fixes #175.
=> Ban valenciae49@yahoo.com.

caravel/policy/eligible_users.py, caravel/tests/helper.py, caravel/tests/test_api.py, caravel/tests/test_listings.py
Fixes #173, to the best as I can see. I've added support for search, new/edit listing, and inquiry messages.
=> Ensure that Marketplace supports UTF-8.

caravel/policy/eligible_users.py, caravel/tests/helper.py, caravel/tests/test_listings.py
Test Site: https://add-slack-integration-dot-caravel-code-reviews.appspot.com/
=> Add Slack integration to main controller

caravel/controllers/listings.py, caravel/policy/eligible_users.py, caravel/templates/layout.html, caravel/tests/helper.py, caravel/tests/test_dos.py
This also adds more tests.
```
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
caravel/__init__.py                            15     15     0%
caravel/controllers/__init__.py                 0      0   100%
caravel/controllers/api.py                     35     16    54%
caravel/controllers/forms.py                   60     50    17%
caravel/controllers/listings.py               134     73    46%
caravel/daemons/__init__.py                     0      0   100%
caravel/daemons/delete_old_photos.py            5      5     0%
caravel/daemons/migration.py                   10     10     0%
caravel/daemons/replication.py                 36     36     0%
caravel/policy.py                              12     12     0% …
```
=> Make quota denials more red

README.md, circle.yml, requirements_dev.txt
This way we get bugged if things aren't tested.
=> Add coveralls coverage to testing dependency

caravel/policy/eligible_users.py
Says in on the can (see support request).
=> Allow Lab School emails to post to Marketplace

caravel/policy/eligible_users.py
=> Add Ingleside Condos to whitelist

caravel/policy/eligible_users.py, caravel/utils.py, circle.yml, run_tests.sh
I'm hoping this'll fix the issues people were having with domains.
=> Allow domain suffixes

.gitignore, app.yaml, caravel/model/migration.py, requirements_dev.txt, unit_tests.sh
This also fixes a bug I discovered where https://caravel-code-reviews.appspot.com/foobarsnafu.
=> Clean up handling of virtualenvs

caravel/__init__.py, caravel/daemons/nag_moderators.py, caravel/templates/email/nag_moderators.txt, caravel/tests/test_listings.py, cron.yaml
Fairly rudimentary. This makes sure we never get too behind on moderation.
=> Nag moderators at 9 AM to approve listings

caravel/controllers/listings.py, caravel/templates/listings/fullpage.html, caravel/tests/test_listings.py, caravel/utils/principals.py
This makes it easier for us to see who posted what.
=> Add notice about who posted each listing

caravel/static/default.css, caravel/templates/index.html, caravel/tests/helper.py
This adds a statement from me to the top of the site, once it comes back online.
=> Publicize Update

caravel/utils/principals.py
This should never be hit — but just in case :)
=> Validated emails must end with @uchicago.edu.

caravel/templates/listing_form.html, caravel/tests/test_listings.py
=> making email message a bootstrap alert

caravel/templates/listings/list.html, caravel/tests/test_listings.py
=> fixing price in list view

caravel/__init__.py, caravel/utils/emails.py
This causes hard-to-debug errors when computing code coverage.
=> Fix import cycles

caravel/model/listing.py, caravel/static/default.css, caravel/templates/header.html, caravel/templates/listings/fullpage.html, caravel/templates/search_fail.html, caravel/tests/helper.py, caravel/tests/test_migration.py
Basically, it lets us search via seller: and adds a notice.
=> Index sellers in search

app.yaml, caravel/controllers/custom_fields.py, caravel/controllers/listings.py
For strange reasons, App Engine's login_url() RPC doesn't work (but login: required does) so this is a convenient workaround.
=> App engine workaround

caravel/controllers/moderation.py, caravel/static/js/moderation.js, caravel/templates/moderation/view.html
Fairly rudimentary- it just deletes the listing in question.
=> Add deny button

caravel/controllers/listings.py, caravel/templates/header.html
=> removing outdate help page

caravel/controllers/listings.py
Rushing since this is a security bug :(
=> Prevent malicious users from hiding listings.

caravel/controllers/moderation.py, caravel/static/js/moderation.js, caravel/templates/moderation/view.html
Right now the moderation view is really annoying to use — the buttons keep jumping around, the sort order is off, and we use too much horizontal space. I'm hoping this PR will help it somewhat.
=> Sort entries by email in moderation view

caravel/controllers/custom_fields.py, caravel/controllers/listings.py, caravel/storage/config.py, caravel/templates/listings/fullpage.html, caravel/tests/helper.py, caravel/tests/test_listings.py, caravel/tests/test_listings_new_listing_expect.txt, caravel/tests/test_listings_post_inquiry_expect.txt, caravel/tests/test_listings_post_inquiry_with_cnetid_expect.txt, caravel/tests/test_listings_publish_listing_expect.txt, caravel/utils/principals.py
Fairly basic. Primarily, this adds a "Suggest Changes" box that lets people make suggestions to a listing that we can then moderate.
=> Allow edit and mark as sold for unauthenticated users.

caravel/controllers/listings.py, caravel/daemons/delete_old_photos.py, caravel/daemons/migration.py, caravel/model/full_text.py, caravel/model/listing.py, caravel/model/moderation.py, caravel/model/priced.py, caravel/model/temporal.py, caravel/static/default.css, caravel/templates/listings/access_panel.html, caravel/templates/listings/fullpage.html, caravel/tests/test_listings.py, caravel/tests/test_listings_bump_listing_expect.txt, caravel/tests/test_listings_edit_listing_expect.txt, caravel/tests/test_listings_indexing_expect.txt, caravel/tests/test_listings_new_listing_expect.txt, caravel/tests/test_listings_new_listing_with_cnetid_expect.txt, caravel/tests/test_listings_old_listing_expect.txt, caravel/tests/test_listings_post_inquiry_expect.txt, caravel/tests/test_listings_post_inquiry_with_cnetid_expect.txt, caravel/tests/test_listings_publish_listing_expect.txt, caravel/tests/test_listings_publish_listing_with_cnetid_expect.txt, caravel/tests/test_migration.py
This one ended up being trickier than I had expected :(
Main changes:
1. Listings are no longer bumped to the top when edited.
2. Listings are still visible, but do not come up in searches, after 30 days.
#209 #119 #216
=> Expire listings after 30 days

app.yaml, caravel/controllers/api.py
Emergency PR to temporarily block API requests from slowing down the service.
=> Block API requests

caravel/templates/index.html
I feel like this has probably run its course.
=> Remove notice about Marketplace hack.

caravel/model/full_text.py
Temporary hack to increase the amount of time entities spend in cache, in the hopes of cutting costs.
=> Increase memcache expiration.

caravel/templates/header.html, caravel/templates/index.html, caravel/tests/test_listings_new_listing_expect.txt, caravel/tests/test_listings_new_listing_with_cnetid_expect.txt, caravel/tests/test_listings_publish_listing_expect.txt, caravel/tests/test_listings_publish_listing_with_cnetid_expect.txt, caravel/tests/test_listings_search_expect.txt
We get a lot of questions (2-4/week-ish) from Alumni/BSD/Hospital people who _really, really_ want to log in to Marketplace. (Even though they don't need it to do post listings or send inquiries!)
State: We're still discussing whether this is a okay. Please do not merge yet.
=> Remove confusing login button on home page

caravel/model/full_text.py
Right now https://add-profiler-dot-hosted-caravel.appspot.com/?offset=1000 is pretty slow. Increasing the batch size should help somewhat.
=> Increase search batch size
