uchicago-sg/caravel

main.py, static/loadtest.js
This very sneaky hack allows us to measure a) web page parity and b) resistance to realistic load. I've added the following tracking code to the bottom of the old page `<head>`:
<script src="https://hosted-caravel.appspot.com/static/loadtest.js"></script>
We're already replicating database writes... and will see what the next 24 hours have in store for us.
=> Ensure load parity in Marketplace 2.0

app.yaml, main.py, static/loadtest.js
Google App Engine supports a neat feature where local versions of apps have full access to the remote datastore — kinda like tunneled SQL access. Enabling it makes it considerably easier to run ad-hoc updates (such as renaming record keys) without changing the code on the server.
=> Enable remote_api

templates/index.html, templates/layout.html
This adds: an a) `<meta name="viewport">` tag telling the browser to the native pixels; and b) styling that makes images full width.
=> Fix styling on mobile

live_migration.py, main.py, models.py, search.py, static/loadtest.js, templates/index.html
Not only do the commits make more sense, the code does, too. Please let me know if you have any questions.
Since it's also performance related, I removed the old emailing feature (since the App Engine console has a fancy new exception livestream view), and add a check for /favicon.ico, a file loaded by the browser on every request (!). SInce this would trigger an additional cache miss, it seemed pertinent.
With regard to searching: I'm thinking of making a series of "shards" (lists of keys) where each list contains all the entities with the given word. That way, a search becomes a two-step process: a) (in parallel) look up shards, and b) look up keys for the first N shards. That should be enough, but we'll need to figure out pagination, as well.
I also switched from the New DB to just DB …
=> Add (cleaner) search caching

live_migration.py
fixes #16 
I think paragraph tags are the only things that are showing up in the description so that is all I removed.
=> removing <p> and </p> tags from json scraper

live_migration.py, photos.py
Since we've both just made goofs that made it into "production," I'm going to try and set up a continuous deployment script, so that branches are automatically deployed to App Engine. That will save us time and help prevent these bugs in the future.
In the interim, please read over these changes :)
=> Fix syntax error in live_migration.py and typo in photos.py

caravel/storage/cache.py
This ensures that we can successfully invalidate entries in the runtime cache.
=> Fix caching bug

caravel/storage/entities.py, caravel/storage/helpers.py, requirements.txt, vendor/inflect.py
While playing around with the site, I noticed that "cat" and "cats" got dramatically different result sets. This patch should correct this bug; unfortunately, I will (again, sigh) require reindexing the dataset, which is happening unfortunately often. Testing it locally does work, however, and you can at least test the singularization of search terms:
Before: https://hosted-caravel.appspot.com/
After: https://add-inflect-support-dot-hosted-caravel.appspot.com/
=> Add singularization to search backend

caravel/daemons/replication.py
For silly reasons, the _pull GET requests were being cached (dunno what changed); adding this behavior blocks it.
=> Allow external POST to _pull

caravel/storage/cache.py, caravel/storage/entities.py, caravel/storage/helpers.py, caravel/templates/index.html, caravel/testing/integration_test.py
This was really bugging me :/
Largely, this just simplifies the way we handle this stuff in `caravel/storage/helpers.py` — and also makes adding helpers like these easier in the future.
=> Make cache return entities instead of dicts

caravel/controllers/listings.py, caravel/static/js/continuation.js, caravel/storage/helpers.py, caravel/templates/index.html, caravel/templates/index_continuation.html, caravel/templates/listing_show.html, caravel/templates/listings/fullpage.html, caravel/templates/listings/inline.html
It's a fairly involved update, but I think the result is worth it. Please let me know if anything looks funny.
Note that this exposes some of the problems we have on misses — because they're not parallelized, it will sometimes take almost 3s to render the fragment. There's stuff we can do to improve this, but it seemed out of scope.
Tagging with #11.
=> Load more entries when near the end

caravel/daemons/replication.py
The code in the production version now uses OpenURI (which handles redirects and HTTPS) — but it only does GET. As a result, we now need to revert back to GET in order to properly handle _pull requests. (Also WTForms requires CSRF protection on all POSTs.)
=> Re-update replication endpoint because Ruby is hard

app.yaml, caravel/__init__.py
Using this API, we can go to the following page to view the number, and type, of operations per request.
https://add-rpc-tracing-dot-hosted-caravel.appspot.com/_ah/stats
Hopefully, this'll help fix the read ops bug from earlier.
=> Add RPC tracing via appstats

caravel/storage/helpers.py
Currently, we add hundreds of datastore_v3.Next Small RPCs, which throws us over the 0.05 MM ops daily limit. Changing to a batched fetch should fix this problem.
=> Switch to batched datastore_v3.Next RPCs on fetch

caravel/controllers/listings.py, caravel/templates/header.html
I noticed that some parts of the code were using `session["email"]` and others `session["validated"]`; if we just do `session["email"]`, our lives get somewhat easier.
This pull request also fixes the weird bug where viewing a listing puts you into that session.
=> Remove ambiguous session.validated variable

caravel/static/default.css, caravel/templates/header.html
I think I broke something in a merge conflict somewhere. I also swizzled things a bit so that the logo appears next to the title on mobile, but I'm not opinionated one way or another. Oh, and I also removed some old CSS that was adding underlines to the user menu.
Before:
After:
=> Ensure that header appears inline on desktop

app.yaml, caravel/__init__.py, caravel/controllers/listings.py, caravel/storage/cache.py, caravel/storage/entities.py, caravel/storage/helpers.py
(Branch name is a bit of a misnomer.)
Before, we'd spend about 3s on every request recomputing the singularized forms of each word in every entity; this patch makes it better. Next — parallel RPCs!
=> Cache inflected words from entity

caravel/controllers/listings.py, caravel/storage/entities.py, caravel/storage/helpers.py, caravel/templates/listings/fullpage.html
Fairly simple- so that we can show how much interest there is in each listing.
Test URL: https://add-buyer-tracking-dot-hosted-caravel.appspot.com/
=> Add tracking for interested buyers

caravel/controllers/listings.py
Currently, if signed in, people can post listings as other people.
=> Ensure that people don't forge emails.

caravel/templates/email/inquiry.html, caravel/templates/email/inquiry.txt, caravel/templates/email/welcome.html, caravel/templates/email/welcome.txt
It may help us when tracking abuse users. There are legitimate privacy concerns however.
Thoughts? The first case is only for people who are placing inquiries, and the second is when they're about to place a listing. In both cases we already know their email (and hence name), as well as their affiliation with this university.
Test URL: https://show-remote-ip-dot-hosted-caravel.appspot.com
=> Show remote IP address when sending messages

app.yaml
ITS has approved our TLS certificate, so I figure we might as well enable it.
=> Ensure that all requests are secure by default.

circle.yml
Right now these test instances use CPU, which is just pushing us over the limit. If we can separate it out, I suspect our CPU costs will go down.
=> Move test instances to separate app

caravel/controllers/listings.py, caravel/templates/listings/fullpage.html
Fairly rudimentary. I was using this on master... and it feels useful enough to keep long term. Thoughts? Are there other things that might be good to know?
By the way- it uses the existing App Engine users API — so as long as you're signed into Gmail with your App Engine admin account, it should show up. You can disable it for demos by adding ?external.
Test instance: er, prod hotfix, so master, but also https://add-handy-debug-view-dot-hosted-caravel.appspot.com.
Incidentally, all these test versions keep burning CPU time. It might be wise to create a separate App ID just for them...
=> Add debug output to listing view

circle.yml
Right now we're uploading ./venv, which contains many, many files, on each push. This will hopefully speed things up a bit.
=> Actually remove auto-created venv symlink

circle.yml
Currently we are _only_ deploying code to caravel-code-reviews.
=> Make sure master is still deployed

caravel/controllers/api.py, caravel/controllers/listings.py, caravel/tests/helper.py, caravel/tests/test_api.py, caravel/tests/test_listings.py
The `"foo" in page.data` pattern felt a little hokey, so here's a new version that is a bit more complete. It accounts for coverage slightly differently, but in general:
```
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
caravel/__init__.py                            15     15     0%
caravel/controllers/__init__.py                 0      0   100%
caravel/controllers/api.py                     35     16    54%
caravel/controllers/forms.py                   50     43    14%
caravel/controllers/listings.py               168     78    54%
caravel/daemons/__init__.py                     0      0   100%
caravel/daemons/delete_old_photos.py            5      5     0%
caravel/daemons/migration.py                   10 …
```
=> Formalize Test Expectations

caravel/templates/listings/list.html, circle.yml
listing doesn’t have the property for thumbnail_url, maybe this will
work
=> changing from thumbnail_url to photos

caravel/controllers/custom_fields.py, caravel/controllers/forms.py, caravel/static/default.css, caravel/tests/test_listings.py
The lazy person's path to Shibboleth logins. Right now there's no additional verification — but once we add moderation that can feed into the verification level of each email.
=> Add App Engine users to authenticate to Marketplace

caravel/model/listing.py, caravel/tests/test_migration.py
Fairly rudimentary. This should prevent the spam we were getting earlier (plus fix the missing photos that are showing up on the test instance).
=> Avoid spamming users on schema updates

caravel/controllers/api.py, caravel/controllers/listings.py, caravel/model/full_text.py, caravel/model/listing.py, caravel/model/moderation.py, caravel/tests/test_api.py, caravel/tests/test_listings.py, index.yaml
Also fairly rudimentary. This brings us (almost) up to parity with the old site.
=> Add support for full-text search

caravel/controllers/listings.py, caravel/templates/header.html, caravel/templates/listings/fullpage.html, caravel/utils/__init__.py, caravel/utils/tor.py, index.yaml
Fairly rudimentary. We have a local cache, expiring every hour, that downloads the full list of exit nodes from https://check.torproject.org/exit-addresses. Using that list, we block new listings, edits, and inquiries.
=> Block requests from Tor to Marketplace

caravel/__init__.py, caravel/model/inquiry.py, caravel/model/listing.py, caravel/model/migration.py, caravel/model/rate_limits.py, caravel/storage/dos.py, caravel/utils/emails.py, caravel/utils/principals.py
This automatically flags inquiries and listings that come from the same email faster than 4/day. It might still get a lot of people, but we can tweak as necessary.
=> Rate limit new listings and inquiries

caravel/__init__.py, caravel/daemons/migration.py, caravel/utils/emails.py, cron.yaml
Primarily, this change spreads the cache invalidations out a bit, reducing the total number of index writes — but the bigger change was just finishing the "update schema" MapReduce.
=> Reduce background writes

caravel/controllers/api.py, caravel/controllers/listings.py, caravel/model/full_text.py
Currently, we load every listing in memory, which makes the home page really slow. This change fixes that.
=> Prevent OoM on home page load

caravel/model/full_text.py
Currently every search needlessly requests `fts:`, which can be avoided by using another small query. (As it stands, `fts:` is cleared on every update, so we're basically already requesting it.)
=> Fix full text indexing

caravel/__init__.py, caravel/templates/listing_form.html, caravel/templates/listings/fullpage.html, caravel/templates/listings/thumbnail.html, caravel/tests/helper.py, caravel/tests/test_listings.py
I realized on Wednesday that we never really talked about showing people's emails, so I un-showed them, pending further policy discussion.
=> Temporarily hide emails

caravel/static/js/moderation.js
Previously, we would alert whenever we succeeded, which is silly.
=> Get rid of the annoying XHR alert message.

app.yaml
Reverts uchicago-sg/caravel#227 because it has broken the site three days in a row.
=> Revert "remove api validation"

caravel/controllers/listings.py
Right now, a bunch of people are getting emails that send them to hosted-caravel.appspot.com domains. This fixes that (i'm also working on the email side).
=> Bounce requests back to proper host.

caravel/model/full_text.py
It's a bit of a hack, but it seems to reduce latency to around 600ms on the home page... as well as speeding up the API. I'm going to keep poking to see if there's anything else to cut out.
Before you merge- I'm a little worried about the feature impacts of this patch. I don't think this integration is tested (because the stubs don't handle this case), and I want to make sure this works in practice. I've played with the test instance somewhat, but can you test it as well?
https://prevent-reloading-keywords-dot-caravel-code-reviews.appspot.com
=> Avoid reloading keywords protobuf on each load

caravel/__init__.py, caravel/controllers/listings.py, caravel/controllers/moderation.py, caravel/static/default.css, caravel/static/js/moderation.js, caravel/templates/layout.html, caravel/templates/moderation/automod.html, caravel/templates/moderation/view.html, caravel/templates/plain_layout.html, caravel/tests/test_automod.py, caravel/tests/test_automod_automod_expect.txt, caravel/tests/test_automod_control_panel_expect.txt, cron.yaml
Currently, moderations are approved by a human moderator (myself), who is hoping to graduate this quarter. The Auto-Moderator is a toggleable listing and inquiry approver that simulates a human moderator with some dumb blacklisting heuristics. By running it every hour, we can hopefully reduce the volume of listings to moderate.
=> Add automatic moderation

caravel/templates/moderation/automod.html
Currently https://marketplace.uchicago.edu/moderation does not work, because I am a dummy and did the tags wrong.
Old: https://marketplace.uchicago.edu/moderation
New: https://fix-mismatch-dot-caravel-code-reviews.appspot.com/moderation
=> Fix mismatched end tag

app.yaml, caravel/controllers/listings.py, caravel/controllers/moderation.py, caravel/daemons/delete_old_photos.py, caravel/daemons/migration.py, caravel/daemons/nag_moderators.py, caravel/templates/moderation/view.html, caravel/tests/test_automod_automod_expect.txt, caravel/tests/test_automod_control_panel_expect.txt
It looks like the problem for Cron was dumber than I thought: a Flask pre-filter that was constantly redirecting invocations off-site. WIth some patching (and manual `appcfg.py` to prod :[ ) I think I've finally fixed all the bugs.
We now have a working Marketplace auto moderator!
=> Fix wonky redirects bug
